#!/usr/bin/env bash
#
# start.sh — start (or restart) SwarmClaw via Docker Compose.
#
# - Ensures the persistent data/ dir and .env.local exist.
# - Guarantees a reboot-surviving restart policy (adds an override only if the
#   upstream compose file does not already declare one).
# - Brings the stack up. Default: `docker compose up -d --build` (builds from the
#   cloned repo). Set SWARMCLAW_NO_BUILD=1 to pull the prebuilt image instead.
#
set -euo pipefail

APP_DIR="${SWARMCLAW_APP_DIR:-/opt/swarmclaw}"
PORT="${SWARMCLAW_PORT:-3456}"
SWARMCLAW_SERVICE="${SWARMCLAW_SERVICE:-swarmclaw}"

# Provider CLIs installed inside the container by default so the bundled
# claude-code / codex providers work out of the box. Format: "pkg:binary".
# Disable with SWARMCLAW_INSTALL_CLIS=0; customise with SWARMCLAW_CLI_SPECS.
SWARMCLAW_INSTALL_CLIS="${SWARMCLAW_INSTALL_CLIS:-1}"
SWARMCLAW_CLI_SPECS="${SWARMCLAW_CLI_SPECS:-@anthropic-ai/claude-code:claude @openai/codex:codex}"

log()  { printf '%s [swarmclaw] %s\n'        "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }
err()  { printf '%s [swarmclaw][ERROR] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >&2; }
die()  { err "$*"; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"; }

if   [ "$(id -u)" -eq 0 ];                 then SUDO=""
elif command -v sudo >/dev/null 2>&1;      then SUDO="sudo -n"
else SUDO=""; fi

# docker compose wrapper: prefer the v2 plugin, fall back to legacy docker-compose.
dc() {
  if $SUDO docker compose version >/dev/null 2>&1; then
    $SUDO docker compose "$@"
  elif command -v docker-compose >/dev/null 2>&1; then
    $SUDO docker-compose "$@"
  else
    die "neither 'docker compose' nor 'docker-compose' is available"
  fi
}

have_compose_file() {
  [ -f docker-compose.yml ] || [ -f docker-compose.yaml ] || \
  [ -f compose.yml ]        || [ -f compose.yaml ]
}

# Add a restart-policy override ONLY when the upstream compose lacks one.
# Override sets a scalar key per service (no volumes) to avoid duplicate-mount errors.
ensure_restart_policy() {
  if [ -f "${APP_DIR}/docker-compose.override.yml" ]; then
    log "docker-compose.override.yml already present — keeping it"
    return 0
  fi
  if dc config 2>/dev/null | grep -qE '^[[:space:]]*restart:'; then
    log "Restart policy already declared by compose — no override needed"
    return 0
  fi
  log "Upstream compose has no restart policy — writing docker-compose.override.yml"
  {
    echo "# Generated by start.sh so SwarmClaw restarts after node reboot."
    echo "services:"
    dc config --services | while IFS= read -r svc; do
      [ -n "$svc" ] || continue
      printf '  %s:\n    restart: unless-stopped\n' "$svc"
    done
  } > "${APP_DIR}/docker-compose.override.yml"
}

# Install the provider CLIs (Claude Code, OpenAI Codex) inside the running
# container so the claude-code / codex agent providers work by default.
# Best-effort and idempotent: never fails the deploy; skips packages already present.
install_provider_clis() {
  if [ "$SWARMCLAW_INSTALL_CLIS" != "1" ]; then
    log "Provider CLI install disabled (SWARMCLAW_INSTALL_CLIS=0)"
    return 0
  fi
  log "Ensuring provider CLIs in container '${SWARMCLAW_SERVICE}': ${SWARMCLAW_CLI_SPECS}"
  # shellcheck disable=SC2086  -- intentional word-splitting of the spec list
  dc exec -u root -T "$SWARMCLAW_SERVICE" sh -s -- $SWARMCLAW_CLI_SPECS <<'INCONTAINER' || log "Provider CLI install skipped (container not ready or npm unavailable)"
command -v npm >/dev/null 2>&1 || { echo "[cli] npm not found in container; skipping"; exit 0; }
for spec in "$@"; do
  pkg=${spec%%:*}; bin=${spec##*:}
  if command -v "$bin" >/dev/null 2>&1; then
    echo "[cli] already present: $bin"
  elif npm install -g "$pkg" >/dev/null 2>&1; then
    echo "[cli] installed: $pkg"
  else
    echo "[cli] WARN: could not install $pkg"
  fi
done
INCONTAINER
}

main() {
  need docker
  [ -d "$APP_DIR" ] || die "app directory not found: ${APP_DIR} (run install.sh first)"
  cd "$APP_DIR"
  have_compose_file || die "no docker compose file found in ${APP_DIR}"

  mkdir -p "${APP_DIR}/data"
  touch    "${APP_DIR}/.env.local"
  chmod 600 "${APP_DIR}/.env.local" 2>/dev/null || true

  # Make sure the Docker daemon is enabled so containers come back after reboot.
  if command -v systemctl >/dev/null 2>&1; then
    $SUDO systemctl enable --now docker >/dev/null 2>&1 || true
  fi

  ensure_restart_policy

  if [ "${SWARMCLAW_NO_BUILD:-0}" = "1" ]; then
    log "Pulling prebuilt image and starting (SWARMCLAW_NO_BUILD=1)"
    dc pull || log "image pull failed — 'up' will build from source if required"
    dc up -d
  else
    log "Building and starting SwarmClaw (docker compose up -d --build)"
    dc up -d --build
  fi

  log "Current containers:"
  dc ps || true

  install_provider_clis

  log "SwarmClaw should be listening on port ${PORT}"
}

main "$@"
