#!/usr/bin/env bash
#
# start.sh — start (or restart) SwarmClaw via Docker Compose.
#
# - Ensures the persistent data/ dir and .env.local exist.
# - Guarantees a reboot-surviving restart policy (adds an override only if the
#   upstream compose file does not already declare one).
# - Brings the stack up. Default: `docker compose up -d --build` (builds from the
#   cloned repo). Set SWARMCLAW_NO_BUILD=1 to pull the prebuilt image instead.
#
set -euo pipefail

APP_DIR="${SWARMCLAW_APP_DIR:-/opt/swarmclaw}"
PORT="${SWARMCLAW_PORT:-3456}"

log()  { printf '%s [swarmclaw] %s\n'        "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }
err()  { printf '%s [swarmclaw][ERROR] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >&2; }
die()  { err "$*"; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"; }

if   [ "$(id -u)" -eq 0 ];                 then SUDO=""
elif command -v sudo >/dev/null 2>&1;      then SUDO="sudo -n"
else SUDO=""; fi

# docker compose wrapper: prefer the v2 plugin, fall back to legacy docker-compose.
dc() {
  if $SUDO docker compose version >/dev/null 2>&1; then
    $SUDO docker compose "$@"
  elif command -v docker-compose >/dev/null 2>&1; then
    $SUDO docker-compose "$@"
  else
    die "neither 'docker compose' nor 'docker-compose' is available"
  fi
}

have_compose_file() {
  [ -f docker-compose.yml ] || [ -f docker-compose.yaml ] || \
  [ -f compose.yml ]        || [ -f compose.yaml ]
}

# Add a restart-policy override ONLY when the upstream compose lacks one.
# Override sets a scalar key per service (no volumes) to avoid duplicate-mount errors.
ensure_restart_policy() {
  if dc config 2>/dev/null | grep -qE '^[[:space:]]*restart:'; then
    log "Restart policy already declared by compose — no override needed"
    return 0
  fi
  log "Upstream compose has no restart policy — writing docker-compose.override.yml"
  {
    echo "# Generated by start.sh so SwarmClaw restarts after node reboot."
    echo "services:"
    dc config --services | while IFS= read -r svc; do
      [ -n "$svc" ] || continue
      printf '  %s:\n    restart: unless-stopped\n' "$svc"
    done
  } > "${APP_DIR}/docker-compose.override.yml"
}

main() {
  need docker
  [ -d "$APP_DIR" ] || die "app directory not found: ${APP_DIR} (run install.sh first)"
  cd "$APP_DIR"
  have_compose_file || die "no docker compose file found in ${APP_DIR}"

  mkdir -p "${APP_DIR}/data"
  touch    "${APP_DIR}/.env.local"
  chmod 600 "${APP_DIR}/.env.local" 2>/dev/null || true

  # Make sure the Docker daemon is enabled so containers come back after reboot.
  if command -v systemctl >/dev/null 2>&1; then
    $SUDO systemctl enable --now docker >/dev/null 2>&1 || true
  fi

  ensure_restart_policy

  if [ "${SWARMCLAW_NO_BUILD:-0}" = "1" ]; then
    log "Pulling prebuilt image and starting (SWARMCLAW_NO_BUILD=1)"
    dc pull || log "image pull failed — 'up' will build from source if required"
    dc up -d
  else
    log "Building and starting SwarmClaw (docker compose up -d --build)"
    dc up -d --build
  fi

  log "Current containers:"
  dc ps || true
  log "SwarmClaw should be listening on port ${PORT}"
}

main "$@"
